CREATE TABLE role
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE users_authorities
(
    user_id        BIGINT NOT NULL,
    authorities_id BIGINT NOT NULL,
    CONSTRAINT pk_users_authorities PRIMARY KEY (user_id, authorities_id)
);

ALTER TABLE users_authorities
    ADD CONSTRAINT fk_useaut_on_role FOREIGN KEY (authorities_id) REFERENCES role (id);

ALTER TABLE users_authorities
    ADD CONSTRAINT fk_useaut_on_user FOREIGN KEY (user_id) REFERENCES users (id);